# Generated by Django 4.1.3 on 2022-11-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Fruit name')),
                ('img', models.ImageField(upload_to='media', verbose_name='Fruit image')),
                ('descripion', models.TextField(verbose_name='Fruit description')),
            ],
            options={
                'verbose_name': 'Fruit',
                'verbose_name_plural': 'Fruits',
            },
        ),
    ]
