# Generated by Django 4.1.3 on 2022-11-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_fruit_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Car name')),
                ('img', models.ImageField(upload_to='media', verbose_name='Car image')),
                ('about', models.TextField(verbose_name='Car about')),
                ('slug', models.SlugField(unique=True, verbose_name='Car slug')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
